mycobot_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    # joint1: { p: 1, d: 0.01, i: 0.01, i_clamp: 1 }
    # joint2: { p: 1, d: 0.01, i: 0.01, i_clamp: 1 }
    # joint3: { p: 1, d: 0.01, i: 0.01, i_clamp: 1 }
    # joint4: { p: 1, d: 0.01, i: 0.01, i_clamp: 1 }
    # joint5: { p: 1, d: 0.01, i: 0.01, i_clamp: 1 }
    # joint6: { p: 1, d: 0.01, i: 0.01, i_clamp: 1 }
    joint1: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    joint2: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    joint3: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    joint4: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    joint5: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
    joint6: { p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0 }

hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - leftfinger_joint
    - rightfinger_joint
  gains:
    gripper_joint: {p: 200, d: 1, i: 5, i_clamp: 1}


joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

gazebo_ros_control:
  pid_gains:
    joint1: { p: 100.0,  d: 0.0, i: 0.0 }
    joint2: { p: 100.0,  d: 0.0, i: 0.0 }
    joint3: { p: 100.0,  d: 0.0, i: 0.0 }
    joint4: { p: 100.0,  d: 0.0, i: 0.0 }
    joint5: { p: 100.0,  d: 0.0, i: 0.0 }
    joint6: { p: 100.0,  d: 0.0, i: 0.0 }
    leftfinger_joint: { p: 200.0,  d: 1.0, i: 5.0 }
    rightfinger_joint: { p: 200.0,  d: 1.0, i: 5.0 }

