controller_list:
  - name: fake_arm_controller
    type: interpolate
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_hand_controller
    type: interpolate
    joints:
      - leftfinger_joint
      - rightfinger_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: Straight
  - group: hand
    pose: Open